num1=int(input("Enter your 1st number:"))
num2=int(input("Enter your 2nd number:"))
print("Addition:",num1+num2)
print("Subtraction:",num1-num2)
print("Multiplication:",num1*num2)
print("Division:",num1/num2)
print("floor division:",num1//num2)
print("modulus:",num1%num2)
print("Double exponent:",num1**num2)